apiVersion: batch/v1
kind: Job # Deployment will automatically restart when killed. Use Pod if not needed
metadata:
  # labels:
  #   k8s-app: research
  # generateName: k5wang-job-train     # Name of Job
  name: k5wang-train-CF10-300  # 50 search epochs / 300 train epochs
  namespace: ecepxie
spec:
  template:
    metadata:
      labels:
        name: k5wang-train
    spec:
      restartPolicy: Never
      containers:
      - name: research
        image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
        imagePullPolicy: Always
        workingDir: /local
        # workingDir: /k5wang-volume/Blood_cell_classification_kaggle/cluster  # dir in which code is executed
        
        command: ["/bin/bash", "/k5wang-volume/Blood_cell_classification_kaggle/cluster/bash/train-CF10-300.sh"]
        
        resources:
          requests:
            memory: "3Gi"
            cpu: "2"
            nvidia.com/gpu: 1
            ephemeral-storage: 10Gi
          limits:
            memory: "3Gi"
            cpu: "2"
            nvidia.com/gpu: 1
            ephemeral-storage: 10Gi

        volumeMounts:
        - name: local
          mountPath: /local
        - name: k5wang-volume     #use your own volume path
          mountPath: /k5wang-volume
        - name: k5wang-volume-datasets
          mountPath: /k5wang-volume-datasets
    
      volumes:
        - name: local
          emptyDir: {}
        - name: k5wang-volume
          persistentVolumeClaim:
            claimName: k5wang-volume
        - name: k5wang-volume-datasets
          persistentVolumeClaim:
            claimName: k5wang-volume-datasets
      nodeSelector:
        gpu-type: "1080Ti"
        nautilus.io/disktype: nvme
