apiVersion: batch/v1
kind: Job # Deployment will automatically restart when killed. Use Pod if not needed
metadata:
  labels:
    k8s-app: research
  generateName: k5wang-job
  namespace: ecepxie
spec:
  template:
    metadata:
      labels:
        k8s-app: research
    spec:
      restartPolicy: Never
      containers:
      - name: research
        image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
        imagePullPolicy: Always
        workingDir: /k5wang-volume/darts/cnn
        command: ["bash","train.sh"]
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
            nvidia.com/gpu: 2
          limits:
            memory: "8Gi"
            cpu: "2"
            nvidia.com/gpu: 2
        volumeMounts:
        - mountPath: /ceph
          name: k5wang-volume
      volumes:
        - name: k5wang-volume
          persistentVolumeClaim:
            claimName: k5wang-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In # Use NotIn for other types
                values:
                - 1080Ti
