apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k5wang-volume-datasets  #use your preferred name
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
